export { Button, type ButtonProps } from './Button/Button';
export { Checkbox, type CheckboxProps } from './Button/Checkbox';
export { VehicleTypeSelect, type VehicleTypeSelectProps, type VehicleType } from './Button/VehicleTypeSelect';
export { ArrowButton, type ArrowButtonProps } from './Button/ArrowButton';
export { NotificationButton, type NotificationButtonProps } from './Button/NotificationButton';
export { EvidenceItemButton } from './Button/EvidenceItemButton';
export { Card, type CardProps } from './Card';
export { Input, type InputProps } from './Input';
export { Dropdown, type DropdownProps, type DropdownOption } from './Dropdown';
export { RadioGroup, type RadioGroupProps, type RadioOption } from './Radio';
export { ChecklistCard, type ChecklistCardProps, type ChecklistItem, type ChecklistSectionData } from './Checklist/ChecklistCard';
export { AccidentCard, type AccidentCardProps } from './Accident/AccidentCard';
export { AccidentCardArrow, type AccidentCardArrowProps } from './Accident/AccidentCardArrow';
export { AccidentStatusBadge, type AccidentStatusBadgeProps, type AccidentStatus } from './Accident/AccidentStatusBadge';
export { BottomTabBar, type TabType } from './BottomTabBar';
export { BackButton, type BackButtonProps } from './BackButton';
export { BottomNavigation, type BottomNavigationProps } from './BottomNavigation';
export { MobileScreen, type MobileScreenProps } from './MobileScreen';
export { SavedDocumentList, type SavedDocumentListProps } from './SavedDocumentList';
export { StatusBar, type StatusBarProps } from './StatusBar';
export { PageHeader } from './PageHeader';
export { VehicleInfoCard, type VehicleInfoCardProps } from './VehicleInfoCard';
export { InsuranceInfoCard, type InsuranceInfoCardProps } from './InsuranceInfoCard';
export { default as GreenModal } from './GreenModal';
export { LoadingScreen } from './Feedback/LoadingScreen';
export { NetworkErrorScreen } from './Feedback/NetworkErrorScreen';
export { SagoScreen, type SagoScreenProps } from './Feedback/SagoScreen';

/*export { Button, type ButtonProps } from './Button/Button';
export { Checkbox, type CheckboxProps } from './Button/Checkbox';
export { VehicleTypeSelect, type VehicleTypeSelectProps, type VehicleType } from './Button/VehicleTypeSelect';
export { ArrowButton, type ArrowButtonProps } from './Button/ArrowButton';
export { NotificationButton, type NotificationButtonProps } from './Button/NotificationButton';
export { Card, type CardProps } from './Card';
export { Input, type InputProps } from './Input';
export { Dropdown, type DropdownProps, type DropdownOption } from './Dropdown';
export { RadioGroup, type RadioGroupProps, type RadioOption } from './Radio';
export { ChecklistCard, type ChecklistCardProps, type ChecklistItem, type ChecklistSectionData } from './Checklist/ChecklistCard';
export { AccidentCard, type AccidentCardProps } from './Accident/AccidentCard';
export { AccidentStatusBadge, type AccidentStatusBadgeProps, type AccidentStatus } from './Accident/AccidentStatusBadge';
export { BottomTabBar, type TabType } from './BottomTabBar';

export { BackButton, type BackButtonProps } from './BackButton';
export { BottomNavigation, type BottomNavigationProps } from './BottomNavigation';
export { MobileScreen, type MobileScreenProps } from './MobileScreen';
export { SavedDocumentList, type SavedDocumentListProps } from './SavedDocumentList';
export { StatusBar, type StatusBarProps } from './StatusBar';
*/
// ❌ 아래 3줄은 features 폴더에 있는 파일들이므로 common/index.ts에서 삭제해야 합니다!
// export { AccidentDateTimeCard } from './Accident/AccidentDateTimeCard';
// export { AccidentTypeCard } from './Accident/AccidentTypeCard';
// export { TrafficConditionCard } from './Accident/TrafficConditionCard';
